# Copyright (c) 2022-2026 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Encoders (Uncomment these two line to add support to your firmware)
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB Underglow (Uncomment these two lines to add support to your firmware)
# RGB quickly drains battery power
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Boost the Bluetooth signal only if having connection issues
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_PHY_2M=n

# Power
# default: 30000 ms
CONFIG_ZMK_IDLE_TIMEOUT=30000
# default: n
CONFIG_ZMK_SLEEP=y
# default: 900000 ms
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_20=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Battery level reporting
# default: n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# default: n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Mouse support
# default: n
CONFIG_ZMK_POINTING=y
