manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: swapper
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
      # support nice_oled and nice_epaper
    # - name: mctechnology17
    # url-base: https://github.com/mctechnology17
    - name: ArtemYurov #new entry
      url-base: https://github.com/ArtemYurov #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      # revision: v0.3 # avoid compatibility break
      # TODO: Try build main eventually
      revision: main
      import: app/west.yml

    - name: zmk-smart-toggle
      remote: swapper
      revision: main

    - name: zmk-auto-layer
      remote: urob
      revision: main # Should match ZMK release.

    # - name: zmk-nice-oled
    #   remote: mctechnology17
    #   revision: main
    - name: nice-view-central-relay
      remote: ArtemYurov
      revision: main
  self:
    path: config
